# 5 - Analyses statistiques (proportion)

L'objectif ici est de reproduire toutes les analyses statistiques de base sur la république en utilisant les occurrences en proportion de la parole totale ou ici plus exactement la proportion d'énoncés mobilisant l'idée de république sur tous les énoncés. 
Pour cela on prend le fichier de base auquel on a ajouté la colonne avec le résultat de la regex en true/false.

In [39]:
import pandas as pd
import plotly.express as px

In [3]:
df = pd.read_csv(
    "../Data/Interim/Data_AN_CSS_République_FDM_proportion.csv", low_memory=False, dtype={"ID_orateur": str}
)

## Analyses temporelles

In [4]:
import datetime
import locale

# Active la locale française (nécessaire pour le format)
locale.setlocale(locale.LC_TIME, "fr_FR.UTF-8")

'fr_FR.UTF-8'

In [5]:
df["dateSeance_ts"] = pd.to_datetime(df["dateSeanceJour"], format="%A %d %B %Y")
df["dateSeance_day"] = df["dateSeance_ts"].dt.normalize()

### Par jours

#### Par jours sur corpus intégral

In [13]:
# Compter True/False par jour
df_daily = (
    df.groupby(df["dateSeance_day"].dt.date)["Republique_FDM_Regex"]
    .value_counts(normalize=True)  # calcule directement les proportions
    .rename("proportion")
    .reset_index()
)

# Garder uniquement les "True"
df_daily_true = df_daily[df_daily["Republique_FDM_Regex"] == True]

# aficher les 25 dates les plus fréquentes sous forme de tableau
table = df_daily_true.sort_values("proportion", ascending=False).head(20)
table

     dateSeance_day  Republique_FDM_Regex  proportion
4        2017-07-03                  True    0.428571
1084     2021-02-01                  True    0.335404
316      2018-07-09                  True    0.264706
1908     2024-03-04                  True    0.255319
1236     2021-06-28                  True    0.248503
839      2020-03-22                  True    0.235294
1092     2021-02-05                  True    0.224684
1262     2021-07-23                  True    0.167598
1377     2022-01-06                  True    0.138728
1088     2021-02-03                  True    0.137255
1880     2024-01-25                  True    0.136364
500      2019-02-11                  True    0.135371
1240     2021-06-30                  True    0.133333
1654     2023-04-05                  True    0.131805
1242     2021-07-01                  True    0.126521
1102     2021-02-12                  True    0.123862
782      2020-01-16                  True    0.120690
322      2018-07-12                  True    0.117428
196      2018-03-13                  True    0.116883
324      2018-07-13                  True    0.113949

**Remarques**
*Le 3 juillet 2017, le 9 juillet 2018, le 4 mars 2024 sont parmis les 5 principales dates car parlement réuni en Congrès*

*le 1 février 2021, le 28 juin 2021, 5 février 2021, le 23 juillet 2021, le 3 février 2021, 30 juin 2021 (et 5 avril 2023 : bilan de la loi), 1er juillet 2021, le 12 février 2021, renvoient quant à eux à la discussion du projet de loi "confortant le respect des principes de la République". **==> Suivre en détail le processus législatif de ce projet de loi car moment central !!***
*On a aussi le 22 mars 2020, très courte séance (commencée à 18h30) sur l’urgence du covid et un hommage*

*6 janvier 2022, 6 juin 2022, 13 mars 2018 : réforme territoriale Nouvelle-Calédonie*

*25 janvier 2024, 8 juillet 2019 et 16 janvier 2020 : accords internationaux avec présence d'expressions comme "gouvernement de la République française", de pays sous forme adjectivable (ex : "république arménienne") ou avec république en miniscule --> moins présent maintenant que exclus*

*11 février 2019 sur "l'école de la confiance"*
*12 et 13 juillet 2018 sur le  projet de loi constitutionnelle pour une Démocratie plus représentative, responsable et efficace*

In [ ]:
# Compter True/False par jour
df_daily = (
    df.groupby(df["dateSeance_day"].dt.date)["Republique_FDM_Regex"]
    .value_counts(normalize=True)  # calcule directement les proportions
    .rename("proportion")
    .reset_index()
)

# Garder uniquement les "True"
df_daily_true = df_daily[df_daily["Republique_FDM_Regex"] == True]

# Graphique
fig_daily = px.line(
    df_daily_true,
    x="dateSeance_day",
    y="proportion",
    title="Proportion occurrences de la 'République' par jour",
    labels={"proportion": "% des occurences", "dateSeance_day": "Date"},
    template="plotly_white",
)

fig_daily.show()

#### Par jour sur corpus annualisé

In [29]:
# Choisir une année
annee = 2022

# Filtrer le DataFrame sur l'année choisie
df_annee = df[df["dateSeance_day"].dt.year == annee]

# Compter True/False par jour
df_daily = (
    df_annee.groupby(df["dateSeance_day"].dt.date)["Republique_FDM_Regex"]
    .value_counts(normalize=True)  # calcule directement les proportions
    .rename("proportion")
    .reset_index()
)

# Garder uniquement les "True"
df_daily_true = df_daily[df_daily["Republique_FDM_Regex"] == True]

# aficher les 25 dates les plus fréquentes sous forme de tableau
table = df_daily_true.sort_values("proportion", ascending=False).head(50)
table

    dateSeance_day  Republique_FDM_Regex  proportion
7       2022-01-06                  True    0.138728
47      2022-02-09                  True    0.088496
68      2022-07-06                  True    0.087273
41      2022-02-03                  True    0.085246
35      2022-01-31                  True    0.078313
53      2022-02-16                  True    0.071429
64      2022-03-01                  True    0.064516
29      2022-01-25                  True    0.054487
92      2022-07-27                  True    0.053292
55      2022-02-17                  True    0.052632
62      2022-02-24                  True    0.048860
43      2022-02-04                  True    0.045752
160     2022-11-22                  True    0.045635
9       2022-01-07                  True    0.044118
70      2022-07-11                  True    0.043042
140     2022-11-03                  True    0.042553
16      2022-01-13                  True    0.041528
128     2022-10-24                  True    0.039752
156     2022-11-18                  True    0.039558
148     2022-11-14                  True    0.038772
142     2022-11-04                  True    0.036932
187     2022-12-11                  True    0.036111
179     2022-12-06                  True    0.035815
20      2022-01-16                  True    0.035533
37      2022-02-01                  True    0.034700
98      2022-08-03                  True    0.028986
165     2022-11-25                  True    0.027638
171     2022-11-30                  True    0.026446
3       2022-01-04                  True    0.024904
197     2022-12-17                  True    0.023529
72      2022-07-12                  True    0.022678
191     2022-12-13                  True    0.022312
104     2022-10-04                  True    0.022195
173     2022-12-01                  True    0.022018
94      2022-07-28                  True    0.021930
167     2022-11-28                  True    0.021802
112     2022-10-11                  True    0.020812
27      2022-01-20                  True    0.020408
175     2022-12-02                  True    0.020385
45      2022-02-08                  True    0.020225
58      2022-02-22                  True    0.018443
24      2022-01-18                  True    0.018307
100     2022-08-04                  True    0.017857
13      2022-01-11                  True    0.017677
51      2022-02-15                  True    0.017621
1       2022-01-03                  True    0.017467
96      2022-08-02                  True    0.017070
150     2022-11-15                  True    0.016393
5       2022-01-05                  True    0.016028
130     2022-10-25                  True    0.015823

In [20]:
# Graphique
fig_daily = px.line(
    df_daily_true,
    x="dateSeance_day",
    y="proportion",
    title="Proportion occurrences de la 'République' par jour",
    labels={"proportion": "% des occurences", "dateSeance_day": "Date"},
    template="plotly_white",
)

fig_daily.show()

### Par semaine

#### Par semaine sur corpus intégral

In [9]:
# Grouper par semaine
df_weekly = (
    df.groupby(df["dateSeance_day"].dt.to_period("W"))["Republique_FDM_Regex"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Transformer la période en datetime (pour l'axe X)
df_weekly["dateSeance_day"] = df_weekly["dateSeance_day"].dt.to_timestamp()

# Garder True uniquement
df_weekly_true = df_weekly[df_weekly["Republique_FDM_Regex"] == True]

# aficher les 25 dates les plus fréquentes sous forme de tableau
table = df_weekly_true.sort_values("proportion", ascending=False).head(20)
table

    dateSeance_day  Republique_FDM_Regex  proportion
293     2021-02-01                  True    0.164128
329     2021-06-28                  True    0.133037
85      2018-07-09                  True    0.108426
67      2018-05-07                  True    0.097122
385     2022-07-04                  True    0.087273
295     2021-02-08                  True    0.081830
59      2018-03-26                  True    0.076539
3       2017-07-03                  True    0.072902
205     2020-01-13                  True    0.068182
381     2022-02-28                  True    0.064516
131     2019-02-11                  True    0.061572
253     2020-07-13                  True    0.057203
55      2018-03-12                  True    0.056604
129     2019-02-04                  True    0.055556
91      2018-07-30                  True    0.050999
127     2019-01-28                  True    0.050293
373     2022-01-31                  True    0.048595
489     2023-12-11                  True    0.046851
161     2019-06-17                  True    0.046405
491     2023-12-18                  True    0.046099

**Remarques**
- 2 premières semaines (+ S6) correspondent aux débats sur la loi « confortant le respect des principes de la République et la lutte contre le séparatisme » 
- 3e semaine correspond au débat sur la démocratie représentative

In [10]:
# Grouper par semaine
df_weekly = (
    df.groupby(df["dateSeance_day"].dt.to_period("W"))["Republique_FDM_Regex"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Transformer la période en datetime (pour l'axe X)
df_weekly["dateSeance_day"] = df_weekly["dateSeance_day"].dt.to_timestamp()

# Garder True uniquement
df_weekly_true = df_weekly[df_weekly["Republique_FDM_Regex"] == True]

# Graphique
fig_weekly = px.bar(
    df_weekly_true,
    x="dateSeance_day",
    y="proportion",
    title="Proportion occurrences de la 'République' par semaine",
    labels={"proportion": "% des occurences hebdomaire", "dateSeance_day": "Semaine"},
    template="plotly_white",
)

fig_weekly.show()

#### Par semaine sur corpus annualisé

In [22]:
# Choisir une année
annee = 2021

# Filtrer le DataFrame sur l'année choisie
df_annee = df[df["dateSeance_day"].dt.year == annee]

# Grouper par semaine
df_weekly = (
    df_annee.groupby(df["dateSeance_day"].dt.to_period("W"))["Republique_FDM_Regex"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Transformer la période en datetime (pour l'axe X)
df_weekly["dateSeance_day"] = df_weekly["dateSeance_day"].dt.to_timestamp()

# Garder True uniquement
df_weekly_true = df_weekly[df_weekly["Republique_FDM_Regex"] == True]

# aficher les 25 dates les plus fréquentes sous forme de tableau
table = df_weekly_true.sort_values("proportion", ascending=False).head(20)
table

   dateSeance_day  Republique_FDM_Regex  proportion
7      2021-02-01                  True    0.164128
43     2021-06-28                  True    0.133037
9      2021-02-08                  True    0.081830
51     2021-09-06                  True    0.042821
3      2021-01-18                  True    0.039950
15     2021-03-08                  True    0.038882
69     2021-11-15                  True    0.038600
19     2021-03-22                  True    0.032878
27     2021-05-03                  True    0.032374
35     2021-05-31                  True    0.032045
13     2021-03-01                  True    0.029249
33     2021-05-24                  True    0.029078
47     2021-07-12                  True    0.028490
39     2021-06-14                  True    0.027094
63     2021-10-25                  True    0.026580
73     2021-11-29                  True    0.023654
71     2021-11-22                  True    0.023588
31     2021-05-17                  True    0.021105
49     2021-07-19                  True    0.020012
41     2021-06-21                  True    0.019828

In [24]:
# Grouper par semaine
df_weekly = (
    df.groupby(df["dateSeance_day"].dt.to_period("W"))["Republique_FDM_Regex"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Transformer la période en datetime (pour l'axe X)
df_weekly["dateSeance_day"] = df_weekly["dateSeance_day"].dt.to_timestamp()

# Garder True uniquement
df_weekly_true = df_weekly[df_weekly["Republique_FDM_Regex"] == True]

# Choisir une année
annee = 2021

# Filtrer le DataFrame sur l'année choisie
df_annee_semaine = df_weekly_true[df_weekly_true["dateSeance_day"].dt.year == annee]

# Graphique
fig_annee_semaine = px.bar(
    df_annee_semaine,
    x="dateSeance_day",
    y="proportion",
    title="Proportion occurrences de la 'République' par semaine en 2024",
    labels={"proportion": "% des occurences mensualisées", "dateSeance_day": "Mois"},
    template="plotly_white",
)

fig_annee_semaine.show()

### Par mois

#### Par mois sur corpus intégral

In [12]:
# Grouper par mois
df_monthly = (
    df.groupby(df["dateSeance_day"].dt.to_period("M"))["Republique_FDM_Regex"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Transformer la période en datetime (pour l'axe X)
df_monthly["dateSeance_day"] = df_monthly["dateSeance_day"].dt.to_timestamp()

# Garder True uniquement
df_monthly_true = df_monthly[df_monthly["Republique_FDM_Regex"] == True]

# aficher les 10 mois les plus fréquents sous forme de tableau
table = df_monthly_true.sort_values("proportion", ascending=False).head(10)
table

    dateSeance_day  Republique_FDM_Regex  proportion
85      2021-02-01                  True    0.089236
109     2022-03-01                  True    0.062500
41      2019-02-01                  True    0.052777
27      2018-07-01                  True    0.052553
29      2018-08-01                  True    0.041885
7       2017-09-01                  True    0.040842
107     2022-02-01                  True    0.040099
93      2021-06-01                  True    0.039917
142     2023-12-01                  True    0.037799
19      2018-03-01                  True    0.036558

In [11]:
# Grouper par mois
df_monthly = (
    df.groupby(df["dateSeance_day"].dt.to_period("M"))["Republique_FDM_Regex"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Transformer la période en datetime (pour l'axe X)
df_monthly["dateSeance_day"] = df_monthly["dateSeance_day"].dt.to_timestamp()

# Garder True uniquement
df_monthly_true = df_monthly[df_monthly["Republique_FDM_Regex"] == True]

# Graphique
fig_monthly = px.bar(
    df_monthly_true,
    x="dateSeance_day",
    y="proportion",
    title="Proportion occurrences de la 'République' par mois",
    labels={"proportion": "% des occurences mensualisées", "dateSeance_day": "Mois"},
    template="plotly_white",
)

fig_monthly.show()

#### Par mois sur corpus annualisé

In [25]:
# Grouper par mois
df_monthly = (
    df.groupby(df["dateSeance_day"].dt.to_period("M"))["Republique_FDM_Regex"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Transformer la période en datetime (pour l'axe X)
df_monthly["dateSeance_day"] = df_monthly["dateSeance_day"].dt.to_timestamp()

# Garder True uniquement
df_monthly_true = df_monthly[df_monthly["Republique_FDM_Regex"] == True]

# Choisir une année
annee = 2021

# Filtrer le DataFrame sur l'année choisie
df_annee_mois = df_monthly_true[df_monthly_true["dateSeance_day"].dt.year == annee]

# aficher les 25 dates les plus fréquentes sous forme de tableau
table = df_annee_mois.sort_values("proportion", ascending=False).head(20)
table

    dateSeance_day  Republique_FDM_Regex  proportion
85      2021-02-01                  True    0.089236
93      2021-06-01                  True    0.039917
87      2021-03-01                  True    0.025989
95      2021-07-01                  True    0.025641
91      2021-05-01                  True    0.024007
97      2021-09-01                  True    0.020833
83      2021-01-01                  True    0.019632
103     2021-12-01                  True    0.018526
101     2021-11-01                  True    0.017078
99      2021-10-01                  True    0.013523
89      2021-04-01                  True    0.012026

In [26]:
# Grouper par mois
df_monthly = (
    df.groupby(df["dateSeance_day"].dt.to_period("M"))["Republique_FDM_Regex"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Transformer la période en datetime (pour l'axe X)
df_monthly["dateSeance_day"] = df_monthly["dateSeance_day"].dt.to_timestamp()

# Garder True uniquement
df_monthly_true = df_monthly[df_monthly["Republique_FDM_Regex"] == True]

# Choisir une année
annee = 2021

# Filtrer le DataFrame sur l'année choisie
df_annee_mois = df_monthly_true[df_monthly_true["dateSeance_day"].dt.year == annee]

# Graphique
fig_annee_mois = px.bar(
    df_annee_mois,
    x="dateSeance_day",
    y="proportion",
    title="Proportion occurrences de la 'République' par mois en 2021",
    labels={"proportion": "% des occurences mensualisées", "dateSeance_day": "Mois"},
    template="plotly_white",
)

fig_annee_mois.show()

#### Par an

In [ ]:
# Grouper par an
df_annee = (
    df.groupby(df["dateSeance_day"].dt.to_period("Y"))["Republique_FDM_Regex"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Transformer la période en datetime (pour l'axe X)
df_annee["dateSeance_day"] = df_annee["dateSeance_day"].dt.to_timestamp()

# Garder True uniquement
df_annee_true = df_annee[df_annee["Republique_FDM_Regex"] == True]

# aficher les 10 mois les plus fréquents sous forme de tableau
table = df_annee_true.sort_values("proportion", ascending=False).head(10)
table

   dateSeance_day  Republique_FDM_Regex  proportion
9      2021-01-01                  True    0.030541
3      2018-01-01                  True    0.021881
1      2017-01-01                  True    0.019772
5      2019-01-01                  True    0.019460
13     2023-01-01                  True    0.018408
11     2022-01-01                  True    0.018088
15     2024-01-01                  True    0.017090
7      2020-01-01                  True    0.016104

In [27]:
# Grouper par année
df_yearly = (
    df.groupby(df["dateSeance_day"].dt.year)["Republique_FDM_Regex"]
    .value_counts(normalize=True)
    .rename("proportion")
    .reset_index()
)

# Garder True uniquement
df_yearly_true = df_yearly[df_yearly["Republique_FDM_Regex"] == True]

# Graphique
fig_yearly = px.bar(
    df_yearly_true,
    x="dateSeance_day",
    y="proportion",
    title="Proportion occurrences de la 'République' par année",
    labels={"proportion": "% des occurences annualisées", "dateSeance_day": "Année"},
    template="plotly_white",
)

fig_yearly.show()

## Par groupes (nécessite d'avoir fait la fusion avec les données de DATAN)

## Par personnel politique / individuellement

***Attention à garder en tête et à discuter : l'analyse en % doit prendre en compte le fait que les ministres parlent plus, et aussi/surtout le nombre d’intervention !!! Donc ce n’est pas un % en termes de temps de parole ou de nombre de mot mais en terme de nombre d’intervention…artéfact statistique à faire attention***

#### Les principaux orateurs sur la période / par législature

#### Ici en % des orateurs ayant mobilisé au moins X fois la "République"

In [11]:
# Compter le nombre de fois où chaque orateur dit "République"
counts = (
    df.groupby("nom_orateur")["Republique_FDM_Regex"]
    .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
    .reset_index()
)

# Calcul de la proportion
counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

# Filtrer les orateurs avec au moins 10 mentions True
filtered = counts[counts["true_mentions"] >= 150]

# Trier par proportion décroissante et garder les 40 premiers
df_top20 = filtered.sort_values("proportion_true", ascending=False).head(40).reset_index(drop=True)

df_top20

                nom_orateur  total_mentions  true_mentions  proportion_true
0            M. Éric Ciotti            1714            174         0.101517
1   M. Jean-Michel Blanquer            2160            180         0.083333
2        M. Alexis Corbière            4300            272         0.063256
3         M. Benjamin Lucas            2815            167         0.059325
4        M. Gérald Darmanin            8451            471         0.055733
5     M. Jean-Luc Mélenchon            4096            218         0.053223
6        Mme Mathilde Panot            3667            166         0.045269
7           M. Stéphane Peu            3866            170         0.043973
8          M. Éric Coquerel            5196            173         0.033295
9        M. Sébastien Jumel            7454            235         0.031527
10     M. Philippe Gosselin            5350            154         0.028785
11        M. Ugo Bernalicis            8863            155         0.017488

In [12]:
# Graphique
fig_top20 = px.bar(
    df_top20,
    x="nom_orateur",
    y="proportion_true",
    title="Top 20 orateurs par proportion de mentions de 'République'",
    labels={"nom_orateur": "Personnel politique", "proportion_true": "% 'République'"},
    template="plotly_white",
)

fig_top20.update_layout(xaxis_tickangle=-45)

fig_top20.show()

#### Par législature

In [19]:
df_16e = df[df["legislature"]== 16]
df_15e = df[df["legislature"]== 15]

In [30]:
# Compter le nombre de fois où chaque orateur dit "République"
counts = (
    df_16e.groupby("nom_orateur")["Republique_FDM_Regex"]
    .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
    .reset_index()
)

# Calcul de la proportion
counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

# Filtrer les orateurs avec au moins 10 mentions True
filtered = counts[counts["true_mentions"] >= 40]

# Trier par proportion décroissante et garder les 40 premiers
df16_top20 = filtered.sort_values("proportion_true", ascending=False).head(40).reset_index(drop=True)

df16_top20

              nom_orateur  total_mentions  true_mentions  proportion_true
0      M. Gérald Darmanin            2140            165         0.077103
1     Mme Élisabeth Borne            1947            130         0.066769
2       M. Benjamin Lucas            2815            167         0.059325
3      Mme Mathilde Panot            1079             54         0.050046
4     M. Antoine Léaument            2419            109         0.045060
5    M. Sébastien Lecornu            1173             42         0.035806
6        M. Gabriel Attal            3002             62         0.020653
7  M. Éric Dupond-Moretti            3330             61         0.018318

In [35]:
# Graphique
fig16_top20 = px.bar(
    df16_top20,
    x="nom_orateur",
    y="proportion_true",
    title="Top 20 orateurs par proportion de mentions de 'République > 40, 16e législature'",
    labels={"nom_orateur": "Personnel politique", "proportion_true": "% 'République'"},
    template="plotly_white",
)

fig16_top20.update_layout(xaxis_tickangle=-45)

fig16_top20.show()

In [36]:
# Compter le nombre de fois où chaque orateur dit "République"
counts = (
    df_15e.groupby("nom_orateur")["Republique_FDM_Regex"]
    .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
    .reset_index()
)

# Calcul de la proportion
counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

# Filtrer les orateurs avec au moins 10 mentions True
filtered = counts[counts["true_mentions"] >= 100]

# Trier par proportion décroissante et garder les 40 premiers
df15_top20 = filtered.sort_values("proportion_true", ascending=False).head(40).reset_index(drop=True)

In [37]:
# Graphique
fig15_top20 = px.bar(
    df15_top20,
    x="nom_orateur",
    y="proportion_true",
    title="Top 20 orateurs par proportion de mentions de 'République > 40 15e législature'",
    labels={"nom_orateur": "Personnel politique", "proportion_true": "% 'République'"},
    template="plotly_white",
)

fig15_top20.update_layout(xaxis_tickangle=-45)

fig15_top20.show()

#### Les principaux orateurs par années/semaines/séances

In [99]:
def top_orateurs_periodique(df, periode="annee", annee=None, semaine=None, jour=None, 
                            date_debut=None, date_fin=None, jours=None,
                            colonne_condition="Republique_FDM_Regex",
                            seuil_min_true=25, top_n=20):

    # --- Filtrage selon la période ---
    if periode == "annee":
        if annee is None:
            raise ValueError("Il faut préciser l'année pour periode='annee'")
        df_filtered = df[df["dateSeance_day"].dt.year == annee]
        titre = f"Top {top_n} du personnel politique mobilisant en % le plus la 'République' en {annee} à l'Assemblée Nationale"

    elif periode == "semaine":
        if annee is None or semaine is None:
            raise ValueError("Il faut préciser l'année et la semaine pour periode='semaine'")
        df_filtered = df[
            (df["dateSeance_day"].dt.isocalendar().year == annee) &
            (df["dateSeance_day"].dt.isocalendar().week == semaine)
        ]
        titre = f"Top {top_n} du personnel politique mobilisant en % le plus la 'République' la {semaine} semaine {annee} à l'Assemblée Nationale"

    elif periode == "jour":
        if jour is None:
            raise ValueError("Il faut préciser la date pour periode='jour'")
        jour_dt = pd.to_datetime(jour).date()
        df_filtered = df[df["dateSeance_day"].dt.date == jour_dt]
        titre = f"Top {top_n} du personnel politique mobilisant le plus en % la 'République' le {jour_dt}"

    elif periode == "intervalle":
        if date_debut is None or date_fin is None:
            raise ValueError("Il faut préciser date_debut et date_fin pour periode='intervalle'")
        debut = pd.to_datetime(date_debut)
        fin = pd.to_datetime(date_fin)
        df_filtered = df[(df["dateSeance_day"] >= debut) & (df["dateSeance_day"] <= fin)]
        titre = f"Top {top_n} du personnel politique mobilisant le plus en % la 'République' du {debut.date()} au {fin.date()}"

    elif periode == "jours":
        if jours is None or not isinstance(jours, (list, tuple)):
            raise ValueError("Il faut fournir une liste de dates pour periode='jours'")
        jours_dt = [pd.to_datetime(j).date() for j in jours]
        df_filtered = df[df["dateSeance_day"].dt.date.isin(jours_dt)]
        titre = f"Top {top_n} du personnel politique mobilisant le plus la 'République' en % lors de X évènement"

    else:
        raise ValueError("periode doit être 'annee', 'semaine', 'jour', 'intervalle' ou 'jours'")

    # --- Comptage des occurrences ---
    counts = (
        df_filtered.groupby("nom_orateur")[colonne_condition]
        .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
        .reset_index()
    )
    counts["proportion_true"] = counts["true_mentions"] / counts["total_mentions"]

    # --- Filtrage par seuil ---
    filtered = counts[counts["true_mentions"] >= seuil_min_true]

    # --- Trier par proportion décroissante et garder top_n ---
    df_top = (
        filtered.sort_values("proportion_true", ascending=False)
        .head(top_n)
        .reset_index(drop=True)
    )

    # --- Graphique ---
    fig = px.bar(
        df_top,
        x="nom_orateur",
        y="proportion_true",
        hover_data=["true_mentions", "total_mentions"],
        title=titre,
        template="plotly_white",
    )
    fig.update_layout(xaxis_tickangle=-45, showlegend=False, yaxis_title="Proportion des interventions totales")
    fig.show()

    return df_top

In [100]:
# Top 10 orateurs en % par année
top_orateurs_periodique(df, periode="annee", annee=2023)

              nom_orateur  total_mentions  true_mentions  proportion_true
0        Mme Sonia Backès             148             33         0.222973
1      M. Gérald Darmanin            1000             94         0.094000
2     Mme Élisabeth Borne            1086             86         0.079190
3      Mme Mathilde Panot             568             37         0.065141
4       M. Benjamin Lucas            1862            110         0.059076
5     M. Antoine Léaument            1440             61         0.042361
6    M. Sébastien Lecornu            1102             38         0.034483
7  M. Éric Dupond-Moretti            1817             31         0.017061

In [56]:
# Top 10 orateurs sur la semaine X de X
top_orateurs_periodique(df, periode="semaine", annee=2021, semaine=6)

                  nom_orateur  total_mentions  true_mentions  proportion_true
0          M. Gérald Darmanin             134             31         0.231343
1         M. François de Rugy              58             11         0.189655
2  M. Jean-Christophe Lagarde              90             16         0.177778
3          M. Alexis Corbière             152             25         0.164474
4     M. Jean-Michel Blanquer             151             24         0.158940
5            M. Xavier Breton              67             10         0.149254
6           Mme Anne Brugnera             280             17         0.060714

In [57]:
# Top 10 orateurs en % (tel jour) le X 
top_orateurs_periodique(df, periode="jour", jour="2021-02-01")

             nom_orateur  total_mentions  true_mentions  proportion_true
0     M. Gérald Darmanin              27             11         0.407407
1     M. Alexis Corbière              37             11         0.297297
2  M. Jean-Luc Mélenchon              61             11         0.180328

In [ ]:
# Top 10 orateurs en % (sur telle période) du 1er au 16 février 2021
top_orateurs_periodique(df, periode="intervalle", date_debut="2021-02-01", date_fin="2021-02-16")

                   nom_orateur  total_mentions  true_mentions  proportion_true
0     M. Pierre-Yves Bournazel              53             19         0.358491
1       M. Guillaume Vuilletet              50             15         0.300000
2             M. Éric Poulliat             162             40         0.246914
3            M. Francis Chouat              47             11         0.234043
4             M. Xavier Breton             120             28         0.233333
5          M. François de Rugy             173             39         0.225434
6           M. Gérald Darmanin             471            103         0.218684
7   M. Jean-Christophe Lagarde             167             35         0.209581
8             M. Boris Vallaud             133             26         0.195489
9      M. Jean-Michel Blanquer             165             26         0.157576
10          M. Alexis Corbière             357             56         0.156863
11              M. Éric Ciotti              80             12         0.150000
12       M. Pierre Dharréville              98             14         0.142857
13        Mme Marlène Schiappa             325             46         0.141538
14               M. Éric Diard              85             12         0.141176
15            M. Éric Coquerel              72             10         0.138889
16       M. Jean-Luc Mélenchon             102             14         0.137255
17         M. François Pupponi             132             16         0.121212
18             M. Stéphane Peu              95             11         0.115789
19       M. Charles de Courson             207             22         0.106280

In [58]:
# Top 10 orateurs en % sur des jours spécifiques
top_orateurs_periodique(df, periode="jours", jours=["2021-02-01", "2021-02-02", "2021-02-03", "2021-02-4", "2021-02-05"])

                   nom_orateur  total_mentions  true_mentions  proportion_true
0        M. Pierre Dharréville              33             13         0.393939
1             M. Éric Poulliat              97             35         0.360825
2             M. Xavier Breton              53             18         0.339623
3         Mme Marlène Schiappa             117             39         0.333333
4   M. Jean-Christophe Lagarde              77             19         0.246753
5          M. François de Rugy             115             28         0.243478
6             M. Boris Vallaud              88             21         0.238636
7           M. Gérald Darmanin             332             70         0.210843
8        M. Charles de Courson              72             14         0.194444
9               M. Éric Ciotti              68             12         0.176471
10          M. Alexis Corbière             194             29         0.149485
11       M. Jean-Luc Mélenchon              98             14         0.142857
12           M. Florent Boudié             148             18         0.121622
13    Mme Laurence Vichnievsky             163             12         0.073620

#### Analyse discussion du projet de loi séparatisme

In [59]:
# Top 10 orateurs lors de la 1ère discussion du projet de loi séparatisme 
top_orateurs_periodique(df, periode="jours", jours=["2021-02-01", "2021-02-02", "2021-02-03", "2021-02-04", "2021-02-05", "2021-02-08", "2021-02-10", "2021-02-11", "2021-02-12", "2021-02-13", "2021-02-16"])

                   nom_orateur  total_mentions  true_mentions  proportion_true
0     M. Pierre-Yves Bournazel              49             19         0.387755
1       M. Guillaume Vuilletet              50             15         0.300000
2             M. Éric Poulliat             162             40         0.246914
3            M. Francis Chouat              47             11         0.234043
4             M. Xavier Breton             120             28         0.233333
5   M. Jean-Christophe Lagarde             150             35         0.233333
6        M. Pierre Dharréville              60             14         0.233333
7          M. François de Rugy             173             39         0.225434
8           M. Gérald Darmanin             468            103         0.220085
9             M. Boris Vallaud             133             26         0.195489
10        Mme Marlène Schiappa             282             46         0.163121
11     M. Jean-Michel Blanquer             154             25         0.162338
12          M. Alexis Corbière             355             56         0.157746
13              M. Éric Ciotti              80             12         0.150000
14       M. Jean-Luc Mélenchon              98             14         0.142857
15               M. Éric Diard              85             12         0.141176
16            M. Éric Coquerel              72             10         0.138889
17             M. Stéphane Peu              89             11         0.123596
18         M. François Pupponi             132             16         0.121212
19       M. Charles de Courson             207             22         0.106280

In [60]:
# Top 10 orateurs en % lors des discussions du projet de loi séparatisme 
top_orateurs_periodique(df, periode="jours", jours=["2021-02-01", "2021-02-02", "2021-02-03", "2021-02-04", "2021-02-05", "2021-02-08", "2021-02-10", "2021-02-11", "2021-02-12", "2021-02-13", "2021-02-16", "2021-06-28", "2021-06-29", "2021-06-30", "2021-07-01", "2021-01-23"])

                   nom_orateur  total_mentions  true_mentions  proportion_true
0     M. Pierre-Yves Bournazel              52             20         0.384615
1             M. Alain Bruneel              61             20         0.327869
2          Mme Lamia El Aaraje              31             10         0.322581
3       M. Guillaume Vuilletet              76             20         0.263158
4             M. Éric Poulliat             204             52         0.254902
5            M. Francis Chouat              66             16         0.242424
6   M. Jean-Christophe Lagarde             150             35         0.233333
7           M. Gérald Darmanin             479            104         0.217119
8          M. François de Rugy             228             47         0.206140
9        M. Pierre Dharréville              74             15         0.202703
10            M. Xavier Breton             149             30         0.201342
11     Mme Marie-George Buffet              65             13         0.200000
12       Mme Cécile Untermaier              57             11         0.192982
13            M. Boris Vallaud             137             26         0.189781
14          M. Alexis Corbière             476             84         0.176471
15            M. Éric Coquerel             117             19         0.162393
16              M. Éric Ciotti             118             19         0.161017
17     M. Jean-Michel Blanquer             174             28         0.160920
18       M. Jean-Luc Mélenchon             121             19         0.157025
19               M. Éric Diard             143             21         0.146853

In [61]:
# Top 10 orateurs en % lors de la deuxième phase de discussion post débat Sénat 
top_orateurs_periodique(df, periode="jours", jours=["2021-06-28", "2021-06-29", "2021-06-30", "2021-07-01", "2021-01-23"])

           nom_orateur  total_mentions  true_mentions  proportion_true
0     M. Alain Bruneel              28             12         0.428571
1  Mme Lamia El Aaraje              31             10         0.322581
2     M. Éric Poulliat              42             12         0.285714
3     M. Julien Ravier              54             14         0.259259
4   M. Alexis Corbière             121             28         0.231405

### Évolution dans le temps de la fréquence d'utilisation du top X de personnels politiques

In [62]:
def stats_orateur_proportion(df, orateur, periode="semaine", colonne_condition="Republique_FDM_Regex"):
  
    # Filtrer sur l'orateur choisi
    df_orateur = df[df["nom_orateur"] == orateur].copy()
    if df_orateur.empty:
        raise ValueError(f"Aucune donnée trouvée pour l'orateur : {orateur}")

    # Définir la granularité
    if periode == "semaine":
        df_orateur["periode"] = (
            df_orateur["dateSeance_day"].dt.isocalendar().year.astype(str)
            + "-W"
            + df_orateur["dateSeance_day"].dt.isocalendar().week.astype(str)
        )
    elif periode == "mois":
        df_orateur["periode"] = df_orateur["dateSeance_day"].dt.to_period("M").astype(str)
    elif periode == "annee":
        df_orateur["periode"] = df_orateur["dateSeance_day"].dt.year.astype(str)
    else:
        raise ValueError("periode doit être 'semaine', 'mois' ou 'annee'")

    # Compter occurrences par période (total et True)
    df_counts = (
        df_orateur.groupby("periode")[colonne_condition]
        .agg(total_mentions="count", true_mentions=lambda x: (x == True).sum())
        .reset_index()
    )

    # Proportion de True
    df_counts["proportion_true"] = df_counts["true_mentions"] / df_counts["total_mentions"]

    # Moyenne et médiane des occurrences
    moyenne_occ = df_counts["total_mentions"].mean()
    mediane_occ = df_counts["total_mentions"].median()

    # Moyenne et médiane des proportions
    moyenne_prop = df_counts["proportion_true"].mean()
    mediane_prop = df_counts["proportion_true"].median()

    return {
        "moyenne_occurrences": moyenne_occ,
        "mediane_occurrences": mediane_occ,
        "moyenne_proportion": moyenne_prop,
        "mediane_proportion": mediane_prop,
        "df_counts": df_counts,
    }

In [ ]:
# Définir la personne recherchée 
orateur = "M. Gérald Darmanin"

# Statistiques hebdomadaires sur "République"
stats = stats_orateur_proportion(df, orateur, periode="annee", colonne_condition="Republique_FDM_Regex")

print(f"{orateur} - Moyenne/semaine (occurrences) : {stats['moyenne_occurrences']:.2f}")
print(f"{orateur} - Médiane/semaine (occurrences) : {stats['mediane_occurrences']}")
print(f"{orateur} - Moyenne/semaine (proportion)  : {stats['moyenne_proportion']:.2f}")
print(f"{orateur} - Médiane/semaine (proportion)  : {stats['mediane_proportion']:.2f}")

# Voir le détail par période
print(stats["df_counts"].head())

M. Gérald Darmanin - Moyenne/semaine (occurrences) : 1056.38
M. Gérald Darmanin - Médiane/semaine (occurrences) : 897.5
M. Gérald Darmanin - Moyenne/semaine (proportion)  : 0.07
M. Gérald Darmanin - Médiane/semaine (proportion)  : 0.07
  periode  total_mentions  true_mentions  proportion_true
0    2017            1727             20         0.011581
1    2018            1969             36         0.018283
2    2019             974             24         0.024641
3    2020             806             76         0.094293
4    2021             820            149         0.181707

## Genre (nécessite d'avoir fait la fusion)

In [ ]:
df["civ"] = df["civ"].replace({"M.": "Homme", "Mme": "Femme"})

In [ ]:
fig = px.bar(df["civ"].value_counts())
fig.update_layout(
    title="Répartition des genres (civ)", template="plotly_white", showlegend=False
)
fig.show()