In [ ]:
# pour garder trace

# 2-clean&filter

In [ ]:
import pandas as pd

df = pd.read_csv(
    "../data/interim/extract_16.csv", low_memory=False, dtype={"ID_orateur": str}
)
df.shape

(337041, 27)

In [ ]:
df_test = df[df["Code_style"] == "NORMAL"]
# Exclure les prises de parole de "Mme la présidente" et "M. le président"
# Role_debat n'est pas bien identifié, utiliser Nom_orateur
df_test = df_test[~df_test["Nom_orateur"].str.strip().isin(["M. le président", "Mme la présidente"])]
df_test.shape

(219086, 27)

In [ ]:
# Ne garder que les prises de parole et les interruptions
df_bis = df[
    (df["Code_grammaire"] == "PAROLE_GENERIQUE")
    | (df["Code_grammaire"] == "INTERRUPTION_1_10")
]  # ou : df["Code_grammaire"].str.strip().isin(["PAROLE_GENERIQUE", "INTERRUPTION_1_10"])

# Exclure les prises de parole de "Mme la présidente" et "M. le président"
# Role_debat n'est pas bien identifié, utiliser Nom_orateur
df_bis = df_bis[~df_bis["Nom_orateur"].str.strip().isin(["M. le président", "Mme la présidente"])]

df_bis.shape

(215307, 27)

In [ ]:
# Afficher les différences d'index entre df_test et df_bis
index_diff_test_bis = df_test.index.difference(df_bis.index)
index_diff_bis_test = df_bis.index.difference(df_test.index)

print("Lignes dans df_test mais pas dans df_bis :", len(index_diff_test_bis))
print("Lignes dans df_bis mais pas dans df_test :", len(index_diff_bis_test))

# Afficher les premières lignes différentes si besoin
if len(index_diff_test_bis) > 0:
    display(df_test.loc[index_diff_test_bis].head())
if len(index_diff_bis_test) > 0:
    display(df_bis.loc[index_diff_bis_test].head())

Lignes dans df_test mais pas dans df_bis : 3779
Lignes dans df_bis mais pas dans df_test : 0

,UID,SeanceRef,SessionRef,DateSeance,DateSeanceJour,NumSeanceJour,NumSeance,TypeAssemblee,Legislature,Session,...,Ordre_seance,Code_grammaire,Code_style,Code_parole,Role_debat,Nom_orateur,Qualite_orateur,ID_orateur,stime,Texte
3434,CRSANR5L16S2024O1N103,RUANR5L16S2024IDS28011,SCR5A2024O1,20240124140000000,mercredi 24 janvier 2024,1,103,AN,16,Session ordinaire 2023-2024,...,738,RAP_REGLEMENT_2_2,NORMAL,NaN,NaN,Mme Émilie Bonnivard,NaN,721410,14404.40,Ce rappel au règlement se fonde sur l’article ...
3436,CRSANR5L16S2024O1N103,RUANR5L16S2024IDS28011,SCR5A2024O1,20240124140000000,mercredi 24 janvier 2024,1,103,AN,16,Session ordinaire 2023-2024,...,741,RAP_REGLEMENT_2_2,NORMAL,NaN,NaN,Mme Émilie Bonnivard,NaN,721410,14425.11,Je m’opposerai systématiquement à ces pétition...
3474,CRSANR5L16S2024O1N103,RUANR5L16S2024IDS28011,SCR5A2024O1,20240124140000000,mercredi 24 janvier 2024,1,103,AN,16,Session ordinaire 2023-2024,...,796,DISC_ARTICLES_3_9,NORMAL,NaN,NaN,M. Xavier Breton,NaN,330008,14976.59,Je veux être très clair : je défends cet amend...
3477,CRSANR5L16S2024O1N103,RUANR5L16S2024IDS28011,SCR5A2024O1,20240124140000000,mercredi 24 janvier 2024,1,103,AN,16,Session ordinaire 2023-2024,...,800,DISC_ARTICLES_3_9,NORMAL,NaN,NaN,M. Xavier Breton,NaN,330008,15041.82,"Monsieur Balanant, n’hésitez pas à prendre la ..."
3479,CRSANR5L16S2024O1N103,RUANR5L16S2024IDS28011,SCR5A2024O1,20240124140000000,mercredi 24 janvier 2024,1,103,AN,16,Session ordinaire 2023-2024,...,803,DISC_ARTICLES_3_9,NORMAL,NaN,NaN,M. Xavier Breton,NaN,330008,15076.65,"…nous demandons la suppression de ce texte, qu..."

In [ ]:
display(df_test.loc[index_diff_test_bis])

,UID,SeanceRef,SessionRef,DateSeance,DateSeanceJour,NumSeanceJour,NumSeance,TypeAssemblee,Legislature,Session,...,Ordre_seance,Code_grammaire,Code_style,Code_parole,Role_debat,Nom_orateur,Qualite_orateur,ID_orateur,stime,Texte
3434,CRSANR5L16S2024O1N103,RUANR5L16S2024IDS28011,SCR5A2024O1,20240124140000000,mercredi 24 janvier 2024,1,103,AN,16,Session ordinaire 2023-2024,...,738,RAP_REGLEMENT_2_2,NORMAL,NaN,NaN,Mme Émilie Bonnivard,NaN,721410,14404.40,Ce rappel au règlement se fonde sur l’article ...
3436,CRSANR5L16S2024O1N103,RUANR5L16S2024IDS28011,SCR5A2024O1,20240124140000000,mercredi 24 janvier 2024,1,103,AN,16,Session ordinaire 2023-2024,...,741,RAP_REGLEMENT_2_2,NORMAL,NaN,NaN,Mme Émilie Bonnivard,NaN,721410,14425.11,Je m’opposerai systématiquement à ces pétition...
3474,CRSANR5L16S2024O1N103,RUANR5L16S2024IDS28011,SCR5A2024O1,20240124140000000,mercredi 24 janvier 2024,1,103,AN,16,Session ordinaire 2023-2024,...,796,DISC_ARTICLES_3_9,NORMAL,NaN,NaN,M. Xavier Breton,NaN,330008,14976.59,Je veux être très clair : je défends cet amend...
3477,CRSANR5L16S2024O1N103,RUANR5L16S2024IDS28011,SCR5A2024O1,20240124140000000,mercredi 24 janvier 2024,1,103,AN,16,Session ordinaire 2023-2024,...,800,DISC_ARTICLES_3_9,NORMAL,NaN,NaN,M. Xavier Breton,NaN,330008,15041.82,"Monsieur Balanant, n’hésitez pas à prendre la ..."
3479,CRSANR5L16S2024O1N103,RUANR5L16S2024IDS28011,SCR5A2024O1,20240124140000000,mercredi 24 janvier 2024,1,103,AN,16,Session ordinaire 2023-2024,...,803,DISC_ARTICLES_3_9,NORMAL,NaN,NaN,M. Xavier Breton,NaN,330008,15076.65,"…nous demandons la suppression de ce texte, qu..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334609,CRSANR5L16S2024O1N126,RUANR5L16S2024IDS28088,SCR5A2024O1,20240227090000000,mardi 27 février 2024,1,126,AN,16,Session ordinaire 2023-2024,...,397,QOSD_2_2,NORMAL,NaN,NaN,M. Christophe Naegelen,NaN,721486,9949.89,"Madame la ministre déléguée, j’aurais beaucoup..."
334621,CRSANR5L16S2024O1N126,RUANR5L16S2024IDS28088,SCR5A2024O1,20240227090000000,mardi 27 février 2024,1,126,AN,16,Session ordinaire 2023-2024,...,432,QOSD_2_2,NORMAL,NaN,NaN,M. Paul-André Colombani,NaN,719286,10627.90,"Après un premier échec, les négociations conve..."
334627,CRSANR5L16S2024O1N126,RUANR5L16S2024IDS28088,SCR5A2024O1,20240227090000000,mardi 27 février 2024,1,126,AN,16,Session ordinaire 2023-2024,...,445,QOSD_2_2,NORMAL,NaN,NaN,M. Jean-Marc Tellier,NaN,794650,10949.45,"Depuis le début de mon mandat, j’ai pu mesurer..."
334631,CRSANR5L16S2024O1N126,RUANR5L16S2024IDS28088,SCR5A2024O1,20240227090000000,mardi 27 février 2024,1,126,AN,16,Session ordinaire 2023-2024,...,458,QOSD_2_2,NORMAL,NaN,NaN,Mme Christine Loir,NaN,793672,11260.53,Je me fais la porte-parole des commerçants et ...
334637,CRSANR5L16S2024O1N126,RUANR5L16S2024IDS28088,SCR5A2024O1,20240227090000000,mardi 27 février 2024,1,126,AN,16,Session ordinaire 2023-2024,...,471,QOSD_2_2,NORMAL,NaN,NaN,M. Éric Pauget,NaN,718784,11570.75,J’appelle votre attention sur les difficultés ...